runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: |
          setup.cfg
          requirements*.txt

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
